#Tagi jakie może mieć folder
#Defaultowe wartości to pierwszy element tablicy lub przypisana wartość bool
#Wartosc typu 01 odczytujemy jako 0 element z kategorii 1, 1 element z kategorii drugiej
#Dla wartosci logicznych 0 oznacza fałsz, zaś 1 prawde 
[Tags]
gender = ["nonbinary", "female", "male"]
accent = false
diction = ["common", "lecture", "com-emo"]
proper_nouns = false
scientific = false
background_noise = ["no-noise", "high-noise", "med-noise", "low-noise"]